package guiPieces.buildComparators;

import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.HashSet;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

import guiPieces.GuiConstants;
import modelPieces.StatsRow;
import modelPieces.Weapon;

public class CompareMetrics implements ActionListener {
	private Weapon baseModel;
	private JPanel comparator;

	private JButton useCurrentBuild, compareBuilds;
	private JCheckBox enableWeakpoints, enableAccuracy, enableArmorWasting;
	private JTextField build1, build2, build3, build4;
	private JLabel[] metricNames;
	private JLabel[][] outputMatrix;
	
	public CompareMetrics(Weapon toUse) {
		baseModel = toUse.clone();
	}
	
	public JPanel getMetricComparisonPanel() {
		comparator = new JPanel();
		comparator.setLayout(new GridLayout(17, 5));
		comparator.setBackground(GuiConstants.drgBackgroundBrown);
		
		// Top row: "Use curent build" button and 3 checkboxes
		useCurrentBuild = new JButton("Use current build for column 1");
		useCurrentBuild.addActionListener(this);
		comparator.add(useCurrentBuild);
		// Empty JLabel to push checkboxes flush with right side
		comparator.add(new JLabel());
		
		enableWeakpoints = new JCheckBox("Enable Weakpoints");
		comparator.add(enableWeakpoints);
		enableAccuracy = new JCheckBox("Enable Accuracy");
		comparator.add(enableAccuracy);
		enableArmorWasting = new JCheckBox("Enable Armor Wasting");
		comparator.add(enableArmorWasting);
		
		// Second row: "Compare" button and four text fields that user can type builds into
		compareBuilds = new JButton("Compare");
		compareBuilds.addActionListener(this);
		comparator.add(compareBuilds);
		
		build1 = new JTextField();
		comparator.add(build1);
		build2 = new JTextField();
		comparator.add(build2);
		build3 = new JTextField();
		comparator.add(build3);
		build4 = new JTextField();
		comparator.add(build4);
		
		// Rows 3-17: metrics
		metricNames = new JLabel[] {
			new JLabel("Burst DPS:"),
			new JLabel("Sustained DPS:"),
			new JLabel("Additional Target DPS:"),
			new JLabel("Max Num Targets:"),
			new JLabel("Max Multi-Target Damage:"),
			new JLabel("Ammo Efficiency:"),
			new JLabel("% Damage Wasted by Armor:"),
			new JLabel("General Accuracy %:"),
			new JLabel("Weakpoint Accuracy %:"),
			new JLabel("Firing Duration:"),
			new JLabel("Avg TTK:"),
			new JLabel("Avg Overkill %:"),
			new JLabel("Breakpoints:"),
			new JLabel("Utility:"),
			new JLabel("Avg Time to Ignite/Freeze:")
		};
		outputMatrix = new JLabel[15][4];
		for (int row = 0; row < 15; row++) {
			metricNames[row].setFont(GuiConstants.customFont);
			metricNames[row].setForeground(GuiConstants.drgRegularOrange);
			comparator.add(metricNames[row]);
			
			outputMatrix[row] = new JLabel[4];
			for (int col = 0; col < 4; col++) {
				outputMatrix[row][col] = new JLabel();
				outputMatrix[row][col].setFont(GuiConstants.customFont);
				outputMatrix[row][col].setBorder(GuiConstants.orangeLine);
				// JLabels are transparent background, so the brown from underlying JPanel should show through
				// Font color will be set later when metrics get plugged in and compared
				comparator.add(outputMatrix[row][col]);
			}
		}
		
		return comparator;
	}

	@Override
	public void actionPerformed(ActionEvent arg0) {
		Object e = arg0.getSource();
		
		if (e == useCurrentBuild) {
			// Because this combination is generated by the program itself, I'm choosing to bypass input sanitization.
			build1.setText(baseModel.getCombination());
		}
		else if (e == compareBuilds) {
			/*
				First, sanitize the 4 text inputs and return early if any non-empty fields fail validation.
			*/
			String build1ErrorMsg="", build2ErrorMsg="", build3ErrorMsg="", build4ErrorMsg="";
			if (!build1.getText().equals("") && !baseModel.isCombinationValid(build1.getText())) {
				build1ErrorMsg = baseModel.getInvalidCombinationErrorMessage();
			}
			if (!build2.getText().equals("") && !baseModel.isCombinationValid(build2.getText())) {
				build2ErrorMsg = baseModel.getInvalidCombinationErrorMessage();
			}
			if (!build3.getText().equals("") && !baseModel.isCombinationValid(build3.getText())) {
				build3ErrorMsg = baseModel.getInvalidCombinationErrorMessage();
			}
			if (!build4.getText().equals("") && !baseModel.isCombinationValid(build4.getText())) {
				build4ErrorMsg = baseModel.getInvalidCombinationErrorMessage();
			}
			
			if (build1ErrorMsg.length() > 0 || build2ErrorMsg.length() > 0 || build3ErrorMsg.length() > 0 || build4ErrorMsg.length() > 0) {
				// Send a pop-up with the error message(s) and then return early for failure state.
				// TODO: make popup
				return;
			}
		
			/*
				Second, squish the inputs all to the left-most columns to simplify logic later. Do nothing if only one column has a build.
			*/
			ArrayList<String> justifyLeft = new ArrayList<String>();
			justifyLeft.add(build1.getText());
			justifyLeft.add(build2.getText());
			justifyLeft.add(build3.getText());
			justifyLeft.add(build4.getText());
			
			int i = 0, j;
			while (i < justifyLeft.size()) {
				if (justifyLeft.get(i).length() == 0) {
					justifyLeft.remove(i);
				}
				else {
					i++;
				}
			}
			
			int numBuildsToCompare = justifyLeft.size();
			
			if (numBuildsToCompare < 2) {
				// Early exit: if fewer than 2 fields have been filled out when the button gets pressed, do nothing.
				return;
			}
			
			while (justifyLeft.size() < 4) {
				justifyLeft.add("");
			}
			build1.setText(justifyLeft.get(0));
			build2.setText(justifyLeft.get(1));
			build3.setText(justifyLeft.get(2));
			build4.setText(justifyLeft.get(3));
			
			/*
				Third, iterate through all 4 columns and get the metrics (and breakpoints) of each
			*/
			baseModel.setWeakpointDPS(enableWeakpoints.isSelected(), false);
			baseModel.setAccuracyDPS(enableAccuracy.isSelected(), false);
			baseModel.setArmorWastingDPS(enableArmorWasting.isSelected(), false);
			
			// Guaranteed to have at the left-most two columns at this point in the method
			double[][] metricsToCompare = new double[numBuildsToCompare][15];
			StatsRow[][] breakpointsToCompare = new StatsRow[numBuildsToCompare][31];
			for (i = 0; i < numBuildsToCompare; i++) {
				baseModel.buildFromCombination(justifyLeft.get(i), false);
				metricsToCompare[i] = new double[] {
					baseModel.calculateSingleTargetDPS(true),
					baseModel.calculateSingleTargetDPS(false),
					baseModel.calculateAdditionalTargetDPS(),
					baseModel.calculateMaxNumTargets(),
					baseModel.calculateMaxMultiTargetDamage(),
					baseModel.ammoEfficiency(),
					baseModel.damageWastedByArmor(),
					baseModel.getGeneralAccuracy(),
					baseModel.getWeakpointAccuracy(),
					baseModel.calculateFiringDuration(),
					baseModel.averageTimeToKill(),
					baseModel.averageOverkill(),
					baseModel.breakpoints(),
					baseModel.utilityScore(),
					baseModel.averageTimeToCauterize()
				};
				
				breakpointsToCompare[i] = baseModel.breakpointsExplanation();
			}
			
			/*
				Fourth, go row by row and assess if the 2-4 numbers are all equal, or if one is greater than all the others. All equal => yellow font; one greater => one green, the rest red
			*/
			HashSet<Double> distinctMetricValuesForThisRow;
			double bestValue;
			int bestIndex;
			for (i = 0; i < 15; i++) {
				// Convert the array to a Set
				distinctMetricValuesForThisRow = new HashSet<Double>();
				for (j = 0; j < numBuildsToCompare; j++) {
					distinctMetricValuesForThisRow.add(metricsToCompare[j][i]);
				}
				
				// Check if all 2-4 values are equal using a Set
				if (distinctMetricValuesForThisRow.size() == 1) {
					// This special case will indicate that all values are equal
					bestIndex = -1;
				}
				// If there are at least 2 distinct values, find which index is the best
				else {
					bestValue = metricsToCompare[0][i];
					bestIndex = 0;
					for (j = 1; j < numBuildsToCompare; j++) {
						// These specific metrics want to find the lowest positive number
						// TODO: I'd like to improve how these specific metrics are checked for this if statement
						if (i == 6 || i == 10 || i == 11 || i == 12 || i == 14) {
							if (bestValue < 0.0 && metricsToCompare[j][i] >= 0.0) {
								bestValue = metricsToCompare[j][i];
								bestIndex = j;
							}
							else if (bestValue >= 0.0 && metricsToCompare[j][i] >= 0.0 && metricsToCompare[j][i] < bestValue) {
								bestValue = metricsToCompare[j][i];
								bestIndex = j;
							}
						}
						// Everything else wants to find the highest positive
						else {
							if (metricsToCompare[j][i] > bestValue) {
								bestValue = metricsToCompare[j][i];
								bestIndex = j;
							}
						}
					}
				}
				
				/*
					Fifth, fill out the outputMatrix and setForeground() accordingly
				*/
				for (j = 0; j < numBuildsToCompare; j++) {
					outputMatrix[i][j].setText(metricsToCompare[j][i] + "");
					if (bestIndex > -1 && j == bestIndex) {
						outputMatrix[i][j].setForeground(GuiConstants.drgOverclockCleanGreen);
					}
					else if (bestIndex > -1) {
						outputMatrix[i][j].setForeground(GuiConstants.drgNegativeChangeRed);
					}
					else {
						outputMatrix[i][j].setForeground(GuiConstants.drgHighlightedYellow);
					}
				}
				// If a column goes unused, set is value to nothing
				for (j = 3; j >= numBuildsToCompare; j--) {
					outputMatrix[i][j].setText("");
				}
			}
		}
	}
}
